### ISSUE TITLE
"problem copying" on windows 8 and some Windows 10

### ISSUE THREAD

**Issue by wjzhang** [mbedmicro/DAPLink#162] opened 2016-09-27 09:41 UTC
the DAPLink VFS will get the ERROR_ERROR_DURING_TRANSFER  or ERROR_TRANSFER_TIMEOUT error when "problem copying" message on Windows 8 and some Windows 10

**Comment by wjzhang** [comment] 2016-09-27 09:53
![problem copying](https://cloud.githubusercontent.com/assets/9528181/18868557/4196dac8-84db-11e6-9b07-5cfd940fc5db.png)

**Comment by c1728p9** [comment] 2016-09-29 00:44
Hi @wjzhang, thanks for the report. Can you provide more details? It useful to know the board you are using and the version of DAPLink (attach details.txt).

**Comment by wjzhang** [comment] 2016-10-08 00:41
failed information: "An error occurred during the transfer".
caused by one of our engineer build in dropbox. it add some attributes, when drag&drop in MSC, the Windows found it did not match. popup a dialog to continue. if press "yes", it should be working as CMSIS-DAP project. 

![image](https://cloud.githubusercontent.com/assets/9528181/19208887/ea4b07b6-8d32-11e6-9884-e8e4f6ec02ed.png)

[DETAILS.TXT](https://github.com/mbedmicro/DAPLink/files/517328/DETAILS.TXT)


[FAIL.TXT](https://github.com/mbedmicro/DAPLink/files/517327/FAIL.TXT)

**Comment by c1728p9** [comment] 2016-10-08 01:41
It looks like this is firmware for a board that is not yet supported on DAPLink. It has the id of an EFM32 Gecko board - '2000'. Is that correct? Also, could you share the location this code came from? Finally, does this problem only occur on your board or can you get this to occur on other boards?

**Comment by wjzhang** [comment] 2016-10-08 05:37
the test Hex file and firmware are used by our board support STM32F103 MCU. it's base on lpc11u35. compatible wtih https://developer.mbed.org/teams/mbed/wiki/SWDAP. 
this issue will happened on any boards if the drag&drop file add some special attributes when some software create it. like dropbox software. 
for create this issue, you just need create your own the drag&drop hex file in  dropbox sync folder.

**Comment by c1728p9** [comment] 2016-10-08 16:58
Hi @wjzhang, I have been able to reproduce this issue. I'll see if I can track down the cause.

**Comment by c1728p9** [comment] 2016-10-09 00:41
Hi @wjzhang, I was able to identify the issue and created https://github.com/mbedmicro/DAPLink/pull/165 to fix it. Please try this out and let me know if it fixes your problem.

**Comment by wjzhang** [comment] 2016-10-09 03:08
Hi @c1728p9, thanks a lot. it fixed. BTW,  do this change effect Mac OS?

**Comment by c1728p9** [comment] 2016-10-09 06:34
Hi @wjzhang. good to hear this is fixed. I have not yet tried this on Mac OS.

**Comment by c1728p9** [comment] 2016-11-22 20:18
Closing this since #165 has been merged

**Closed by c1728p9** 2016-11-22 20:18 UTC
Labels: bug
